typedef int     ZX;
typedef char    ZFX;
typedef long CZX;
typedef float FD;
typedef short DZX;
#define 如果     if
#define 否则     else
#define 返回     return
#define 常量     const
#define 标准输出 std::cout
#define 行结束   std::endl
#define 标准输入 std::cin
#define 字符串   std::string
#define  空    void
#define 输出 cout
#define 主程序   main
#define 命名空间 namespace
#define 标准 std
#define 整型 int
#define 自动 auto
#define 嵌入汇编 asm
#define 布尔 bool
#define 浮点 float
#define 长整形 long
#define 跳过 break
#define 不同 case
#define 异常 catch
#define 字符型 char
#define 类 class
#define 继续 continue
#define 默认 default
#define 删除 delete
#define 双精 double
#define 动态转换 dynamic_cast
#define 选择 enum
#define 导出 export
#define 导入 extern
#define 跳转 goto
#define 内联 inline
#define 新建 new
#define 操作符 operator
#define 私有 private
#define 公有 public
#define 寄存器 register
#define 友元 friend
#define 伪 false
#define 循环 for
#define 整针 reinterpret_cast
#define 短整型 short
#define 符号 signed
#define 获取 sizeof
#define 静态 static
#define E转T static_cast
#define 结构 struct
#define 转换 switch
#define 模板 template
#define 返回本身 this
#define 抛出 throw
#define 真 true
#define 尝试 try
#define 指出类型 typeid
#define 类型名 typename
#define 联合 union
#define 无符号 unsigned
#define 定义命名 using
#define 虚 virtual
#define 不稳定 volatile
#define 宽字符 wchat_t
